### ISSUE TITLE
Fails to build (‘crc32_combine’ was not declared in this scope)

### ISSUE THREAD

**Issue by fr-an-k** [contra/node-gdal-next#66]
I can't get gdal-next installed on WSL; it used to work a year ago.
It gets stuck on this:

```
../deps/libgdal/gdal/port/cpl_vsil_gzip.cpp:1609:29: error: ‘crc32_combine’ was not declared in this scope; did you mean ‘crc32_combine64’?
```

What am I doing wrong?
When I edit the file it gets overwritten again.

Full output:
<details>

```
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > react-vtree@2.0.4" has unmet peer dependency "react-window@^1.8.5".
warning " > @storybook/preset-create-react-app@3.2.0" has unmet peer dependency "react-scripts@>=3.0.0".
warning "@storybook/preset-create-react-app > @pmmmwh/react-refresh-webpack-plugin@0.4.3" has unmet peer dependency "react-refresh@>=0.8.3 <0.10.0".
warning " > @storybook/react@6.5.16" has unmet peer dependency "require-from-string@^2.0.2".
warning Workspaces can only be enabled in private projects.
[4/4] Building fresh packages...
[-/11] ⡀ waiting...
[2/11] ⢀ mapnik
[-/11] ⢀ waiting...
[4/11] ⢀ gdal-next
error /home/frank/repos/pjk_server/node_modules/gdal-next: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build -j max
Arguments: 
Directory: /home/frank/repos/pjk_server/node_modules/gdal-next
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.11
node-pre-gyp info using node@18.14.0 | linux | x64
node-pre-gyp info check checked for "/home/frank/repos/pjk_server/node_modules/gdal-next/lib/binding/node-v108-linux-x64/gdal.node" (not found)
node-pre-gyp http GET https://gdal-next-binary.s3.amazonaws.com/gdal/v2.8.0/node-v108-linux-x64.tar.gz
node-pre-gyp ERR! install response status 403 Forbidden on https://gdal-next-binary.s3.amazonaws.com/gdal/v2.8.0/node-v108-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not installable for gdal-next@2.8.0 and node@18.14.0 (node-v108 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp WARN Hit error response status 403 Forbidden on https://gdal-next-binary.s3.amazonaws.com/gdal/v2.8.0/node-v108-linux-x64.tar.gz 
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@18.14.0 | linux | x64
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@18.14.0 | linux | x64
gyp info find Python using Python version 3.10.12 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/frank/repos/pjk_server/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/frank/repos/pjk_server/node_modules/gdal-next/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/frank/repos/pjk_server/node_modules/gdal-next/common.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/frank/repos/pjk_server/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/frank/.cache/node-gyp/18.14.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/frank/.cache/node-gyp/18.14.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/frank/repos/pjk_server/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/frank/.cache/node-gyp/18.14.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/frank/repos/pjk_server/node_modules/gdal-next',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@18.14.0 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build', '--jobs', 20 ]
make: Entering directory '/home/frank/repos/pjk_server/node_modules/gdal-next/build'
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/apps/ogr2ogr_lib.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/apps/gdalbuildvrt_lib.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/apps/gdal_translate_lib.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/apps/gdalwarp_lib.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/apps/commonutils.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/frmts/gdalallregister.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/frmts/derived/deriveddataset.o
  CC(target) Release/obj.target/libgdal/deps/libgdal/gdal/frmts/derived/derivedlist.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/swq_select.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/swq_parser.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/swq_op_registrar.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/swq_op_general.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/swq_expr_node.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/swq.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrutils.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrtriangulatedsurface.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrtriangle.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrsurface.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrspatialreference.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrpolyhedralsurface.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrpolygon.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrpoint.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrpgeogeometry.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrmultisurface.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrmultipolygon.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrmultipoint.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrmultilinestring.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrmulticurve.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrlinestring.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrlinearring.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrgeomfielddefn.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrgeometryfactory.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrgeometrycollection.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrgeometry.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrgeomediageometry.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrfielddefn.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrfeaturestyle.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrfeaturequery.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrfeaturedefn.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrfeature.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrcurvepolygon.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrcurvecollection.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrcurve.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrct.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrcompoundcurve.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrcircularstring.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ograssemblepolygon.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ograpispy.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogr_xerces.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogr_srsnode.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogr_srs_xml.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogr_srs_usgs.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogr_srs_pci.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogr_srs_panorama.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogr_srs_ozi.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogr_srs_esri.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogr_srs_erm.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogr_srs_dict.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogr_proj_p.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogr_geocoding.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogr_geo_utils.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogr_fromepsg.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogr_expat.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogr_api.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogr2gmlgeometry.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/gml2ogrgeometry.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrsf_frmts/generic/ogr_gensql.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrsf_frmts/generic/ogremulatedtransaction.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrsf_frmts/generic/ogr_miattrind.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrsf_frmts/generic/ogrunionlayer.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrsf_frmts/generic/ogrsfdriver.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrsf_frmts/generic/ogrregisterall.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrsf_frmts/generic/ogreditablelayer.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrsf_frmts/generic/ogr_attrind.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrsf_frmts/generic/ogrdatasource.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrsf_frmts/generic/ogrmutexedlayer.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrsf_frmts/generic/ogrwarpedlayer.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrsf_frmts/generic/ogrlayerpool.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrsf_frmts/generic/ogrsfdriverregistrar.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrsf_frmts/generic/ogrmutexeddatasource.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrsf_frmts/generic/ogrlayer.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/ogr/ogrsf_frmts/generic/ogrlayerdecorator.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/llrasterize.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/gdaltransformgeolocs.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/gdalgridavx.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/gdalpansharpen.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/gdalmatching.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/gdallinearsystem.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/gdaltransformer.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/gdalproximity.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/contour.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/gdalchecksum.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/gdal_simplesurf.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/gdalsimplewarp.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/gdalwarpkernel_opencl.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/gdalwarpkernel.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/gdal_tps.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/viewshed.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/gdalgridsse.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/gdalgrid.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/gdal_rpc.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/gdalcutline.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/gdalwarpoperation.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/gdalmediancut.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/rasterfill.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/gdalsievefilter.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/gdal_crs.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/thinplatespline.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/gdaldither.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/gdalrasterpolygonenumerator.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/gdal_octave.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/polygonize.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/gdalgeoloc.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/gdalwarper.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/gdalrasterize.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/gdalapplyverticalshiftgrid.o
  CC(target) Release/obj.target/libgdal/deps/libgdal/gdal/alg/delaunay.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdalrescaledalphaband.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdaldefaultasync.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdalgeorefpamdataset.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdalallvalidmaskband.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdaloverviewdataset.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdalproxypool.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdaldllmain.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdaljp2structure.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdalmajorobject.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdaljp2metadatagenerator.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdaldataset.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdalpython.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdalhashsetbandblockcache.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdal_thread_pool.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdalpamrasterband.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdal_mdreader.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdal_misc.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdalmultidim.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/overview.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/nasakeywordhandler.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/rasterio.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdaldrivermanager.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdalproxydataset.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdaljp2box.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdaldriver.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdalpamproxydb.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdalmultidomainmetadata.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdaldefaultoverviews.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdalcolortable.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdalarraybandblockcache.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdalvirtualmem.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdalnodatavaluesmaskband.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdalrasterband.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/rasterio_ssse3.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdalpythondriverloader.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdalopeninfo.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdal_rat.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdalnodatamaskband.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/rawdataset.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdalabstractbandblockcache.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdaljp2metadata.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/tilematrixset.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdaljp2abstractdataset.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdalrasterblock.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdalexif.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/gdalpamdataset.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/mdreader/reader_orb_view.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/mdreader/reader_rapid_eye.o
../deps/libgdal/gdal/gcore/gdalexif.cpp:460: warning: ignoring ‘#pragma optimize ’ [-Wunknown-pragmas]
  460 | #pragma optimize("", off)
      | 
../deps/libgdal/gdal/gcore/gdalexif.cpp:764: warning: ignoring ‘#pragma optimize ’ [-Wunknown-pragmas]
  764 | #pragma optimize("", on)
      | 
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/mdreader/reader_kompsat.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/mdreader/reader_pleiades.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/mdreader/reader_spot.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/mdreader/reader_alos.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/mdreader/reader_landsat.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/mdreader/reader_eros.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/mdreader/reader_digital_globe.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/mdreader/reader_rdk1.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/gcore/mdreader/reader_geo_eye.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/xmlreformat.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cplstringlist.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cplstring.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cplkeywordparser.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cplgetsymbol.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_xml_validate.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_worker_thread_pool.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_vsisimple.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_vsil_win32.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_vsil_webhdfs.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_vsil_unix_stdio_64.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_vsil_tar.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_vsil_swift.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_vsil_subfile.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_vsil_stdout.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_vsil_stdin.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_vsil_sparsefile.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_vsil_s3.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_vsil_plugin.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_vsil_oss.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_vsil_hdfs.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_vsil_gzip.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_vsil_gs.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_vsil_curl_streaming.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_vsil_curl.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_vsil_crypt.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_vsil_cache.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_vsil_buffered_reader.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_vsil_az.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_vsil_abstract_archive.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_vsil.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_vsi_mem.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_vsi_error.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_virtualmem.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_userfaultfd.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_time.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_swift.o
../deps/libgdal/gdal/port/cpl_vsil_gzip.cpp: In member function ‘bool VSIGZipWriteHandleMT::ProcessCompletedJobs()’:
../deps/libgdal/gdal/port/cpl_vsil_gzip.cpp:1609:29: error: ‘crc32_combine’ was not declared in this scope; did you mean ‘crc32_combine64’?
 1609 |                     nCRC_ = crc32_combine(nCRC_, psJob->nCRC_,
      |                             ^~~~~~~~~~~~~
      |                             crc32_combine64
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_strtod.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_string.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_spawn.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_sha256.o
  CXX(target) Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_sha1.o
make: *** [deps/libgdal/libgdal.target.mk:746: Release/obj.target/libgdal/deps/libgdal/gdal/port/cpl_vsil_gzip.o] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory '/home/frank/repos/pjk_server/node_modules/gdal-next/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/frank/repos/pjk_server/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
gyp ERR! System Linux 5.15.90.1-microsoft-standard-WSL2
gyp ERR! command "/home/frank/.nvm/versions/node/v18.14.0/bin/node" "/home/frank/repos/pjk_server/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--jobs=max" "--module=/home/frank/repos/pjk_server/node_modules/gdal-next/lib/binding/node-v108-linux-x64/gdal.node" "--module_name=gdal" "--module_path=/home/frank/repos/pjk_server/node_modules/gdal-next/lib/binding/node-v108-linux-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
gyp ERR! cwd /home/frank/repos/pjk_server/node_modules/gdal-next
gyp ERR! node -v v18.14.0
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/home/frank/.nvm/versions/node/v18.14.0/bin/node /home/frank/repos/pjk_server/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --jobs=max --module=/home/frank/repos/pjk_server/node_modules/gdal-next/lib/binding/node-v108-linux-x64/gdal.node --module_name=gdal --module_path=/home/frank/repos/pjk_server/node_modules/gdal-next/lib/binding/node-v108-linux-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/frank/repos/pjk_server/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
node-pre-gyp ERR! System Linux 5.15.90.1-microsoft-standard-WSL2
node-pre-gyp ERR! command "/home/frank/.nvm/versions/node/v18.14.0/bin/node" "/home/frank/repos/pjk_server/node_modules/gdal-next/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "-j" "max"
node-pre-gyp ERR! cwd /home/frank/repos/pjk_server/node_modules/gdal-next
node-pre-gyp ERR! node -v v18.14.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.11
node-pre-gyp ERR! not ok 
Failed to execute '/home/frank/.nvm/versions/node/v18.14.0/bin/node /home/frank/repos/pjk_server/node_modules/node-gyp/bin/node-gyp.js 
```

</details>

**Comment by yocontra** [comment]
Have you tried the new node-gdal-async library? Forked from this and has many more updates.
